CREATE SCHEMA tpPrograII;
USE tpPrograII;

CREATE TABLE usuarios (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(250) NOT NULL UNIQUE,
contrasenia VARCHAR(500) NOT NULL, 
fecha DATE,
dni INT UNIQUE NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP 
);

INSERT INTO usuarios VALUES 
(DEFAULT,
"jnavarro@udesa.edu.ar",
"justi2005",
"2005-01-05",
46789567,
DEFAULT,
null, 
null
),
(DEFAULT,
"achana@udesa.edu.ar",
"alu2005",
"2005-11-06",
46023567,
DEFAULT,
null, 
null
),
(DEFAULT,
"jzanatta@udesa.edu.ar",
"jochu2006",
"2006-05-12",
47384229,
DEFAULT,
null, 
null
),
(DEFAULT,
"cgarcia@udesa.edu.ar",
"clara2006",
"2006-07-15",
47034789,
DEFAULT,
null, 
null
),
(DEFAULT,
"dgonzalez@udesa.edu.ar",
"delfi2005",
"2005-10-04",
46578902,
DEFAULT,
null, 
null
);

CREATE TABLE productos (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
foto VARCHAR(250) NOT NULL,
nombre VARCHAR (250) UNIQUE NOT NULL,
descripcion TEXT,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP, 
usuarioId INT UNSIGNED, 
FOREIGN KEY (usuarioId) REFERENCES usuarios(id)
);

INSERT INTO productos VALUES 
(DEFAULT, 
"productoUno.png",
"Sudadera Oversize Cremallera",
"Sudadera con capucha confeccionada en hilatura con algodón. Manga larga acabada en puño. Cierre frontal con cremallera metálica.",
DEFAULT, 
null, 
null,
2
),
(DEFAULT, 
"productoDos.png",
"Jeans ZW Collection Relaxed tiro medio",
"Jeans de tiro medio y cintura con trabillas ajustable con cordones a contraste. Cinco bolsillos. Efecto lavado. Cierre frontal con cremallera y botón.",
DEFAULT, 
null, 
null,
4
),
(DEFAULT, 
"productoTres.png",
"Mono Corto Denim TRF Fluido",
"Mono confeccionado en tejido fluido de cuello solapa Manga larga con hombro caído acabada en puño con pliegues. Bolsillo de plastrón en el pecho. Cierre frontal con botones.",
DEFAULT, 
null, 
null,
1
),
(DEFAULT, 
"productoCuatro.png",
"Jersey Rústico",
"Jersey confeccionado en hilatura con algodón. Cuello barco y manga larga.",
DEFAULT, 
null, 
null,
3
),
(DEFAULT, 
"productoCinco.png",
"Trench Corto Efecto Piel",
"Trench corto de cuello solapa y manga larga acabada en puño con trabilla.",
DEFAULT, 
null, 
null,
5
),
(DEFAULT, 
"productoSeis.png",
"Top Halter Satinado ZW Collection",
"Top halter confeccionado en tejido satinado. Espalda descubierta. Bajo asimétrico. Cierre en cuello con botones.",
DEFAULT, 
null, 
null,
2
),
(DEFAULT, 
"productoSiete.png",
"Jeans Z1975 Culotte tiro alto Botones",
"Jeans de tiro alto con bolsillos de plastrón en delantero y espalda. Pernera ancha y corta. Cierre frontal con botones.",
DEFAULT, 
null, 
null,
4
),
(DEFAULT, 
"productoOcho.png",
"Blazer Oversize",
"Blazer oversize de cuello solapa y manga larga con hombreras. Bolsillos de doble vivo en delantero. Bajo con aberturas en espalda. Cierre frontal cruzado con botones.",
DEFAULT, 
null, 
null,
3
),
(DEFAULT, 
"productoNueve.png",
"Sudadera Capucha Bolsillos",
"Sudadera con capucha confeccionada en hilatura con mezcla de algodón. Manga larga. Bolsillos laterales ocultos en costura.",
DEFAULT, 
null, 
null,
5
),
(DEFAULT, 
"productoDiez.png",
"Camiseta Interlock Lavada",
"Camiseta confeccionada en hilatura con mezcla de algodón. Cuello redondo y manga corta caída.",
DEFAULT, 
null, 
null,
2
);

CREATE TABLE comentarios (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
comentario TEXT,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP, 
usuarioId INT UNSIGNED, 
FOREIGN KEY (usuarioId) REFERENCES usuarios(id),
productoId INT UNSIGNED, 
FOREIGN KEY (productoId) REFERENCES productos(id)
);

INSERT INTO comentarios VALUES 
(DEFAULT,
"Divino el color!!",
DEFAULT, 
null, 
null, 
1,
1
),
(DEFAULT,
"Es bastante grande",
DEFAULT, 
null, 
null, 
5,
1
),
(DEFAULT,
"Muy cómodo",
DEFAULT, 
null, 
null, 
2,
1
),
(DEFAULT,
"Es bastante rígido el jean. No me gustó",
DEFAULT, 
null, 
null, 
3,
2
),
(DEFAULT,
"Muy buena calidad",
DEFAULT, 
null, 
null, 
1,
2
),
(DEFAULT,
"Bien ubicados los bolsillos!!!",
DEFAULT, 
null, 
null, 
4,
2
),
(DEFAULT,
"Buenisimo cuando no tenes que ponerte!",
DEFAULT, 
null, 
null, 
1,
3
),
(DEFAULT,
"Muy acordes los talles",
DEFAULT, 
null, 
null, 
5,
3
),
(DEFAULT,
"Estoy feliz con mi compra! Lo super recomiendo",
DEFAULT, 
null, 
null, 
1,
3
),
(DEFAULT,
"No es muy abrigado",
DEFAULT, 
null, 
null, 
3,
4
),
(DEFAULT,
"Re lindo el tejido",
DEFAULT, 
null, 
null, 
2,
4
),
(DEFAULT,
"Buenísimo para verano!!",
DEFAULT, 
null, 
null, 
5,
4
),
(DEFAULT,
"Increíble calidad",
DEFAULT, 
null, 
null, 
3,
5
),
(DEFAULT,
"El color del año!!",
DEFAULT, 
null, 
null, 
1,
5
),
(DEFAULT,
"No paro de usarlo",
DEFAULT, 
null, 
null, 
4,
5
),
(DEFAULT,
"Divino el cuello del top",
DEFAULT, 
null, 
null, 
2,
6
),
(DEFAULT,
"Muy cómodo y arreglado",
DEFAULT, 
null, 
null, 
1,
6
),
(DEFAULT,
"Me pareció muy fina la tela",
DEFAULT, 
null, 
null, 
5,
6
),
(DEFAULT,
"Son bastante largos",
DEFAULT, 
null, 
null, 
1,
7
),
(DEFAULT,
"Me gustaría que vengan en negro",
DEFAULT, 
null, 
null, 
4,
7
),
(DEFAULT,
"Me parecieron muy incómodos",
DEFAULT, 
null, 
null, 
5,
7
),
(DEFAULT,
"Perfecto para el trabajo",
DEFAULT, 
null, 
null, 
2,
8
),
(DEFAULT,
"Muy bien confeccionado",
DEFAULT, 
null, 
null, 
5,
8
),
(DEFAULT,
"El color es soñado!!",
DEFAULT, 
null, 
null, 
1,
8
),
(DEFAULT,
"Muy cómodo",
DEFAULT, 
null, 
null, 
5,
9
),
(DEFAULT,
"La capucha es demasiado grande",
DEFAULT, 
null, 
null, 
1,
9
),
(DEFAULT,
"Es re abrigado",
DEFAULT, 
null, 
null, 
3,
9
),
(DEFAULT,
"Me copa el color, combina con todo",
DEFAULT, 
null, 
null, 
3,
10
),
(DEFAULT,
"Muy fresquita!!",
DEFAULT, 
null, 
null, 
5,
10
),
(DEFAULT,
"Se me rompió al toque. No la recomiendo",
DEFAULT, 
null, 
null, 
1,
10
);
